### ISSUE TITLE
How does one use this with Dokuwiki?

### ISSUE THREAD

**Issue by GlitterHorn** [cziehr/inclform#1]
I'm not sure I really understand how to use this extension. I put a form in my wiki's data/forms/namespace/namespace2 and tried to reference it using:

```
~~INCLFORM=namespace:namespace2~~
```

but it doesn't appear to do anything. The syntax parser is picking it up, since I'm not seeing an error or the above as rendered text. What am I missing?

**Comment by cziehr** [comment]
See https://forum.dokuwiki.org/d/14687-include-script-file-or-add-php-code/5 in DokuWiki forum

**Comment by GlitterHorn** [comment]
Thanks. I use a farm, and that's why it wasn't working.

I created https://github.com/cziehr/inclform/pull/2 to resolve this.

**Comment by cziehr** [comment]
Done. Thanks for the patch!
